# Generated by Django 5.1.6 on 2025-03-03 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_conteiner_location_item_conteiner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('size', models.CharField(max_length=127, verbose_name='Tamanho')),
                ('body_place', models.PositiveSmallIntegerField(choices=[(1, 'Superior'), (2, 'Inferior'), (3, 'Cabeça'), (4, 'Pés')])),
            ],
            bases=('inventory.item',),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.item')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
            ],
            bases=('inventory.item',),
        ),
        migrations.RenameModel(
            old_name='PericibleItem',
            new_name='Food',
        ),
    ]
