# Generated by Django 5.1.6 on 2025-03-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='name',
            field=models.CharField(default='teste', max_length=127, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
